Repository FluidGroup/Brightroom, pull requests merged in 2021-06, with the labels that each got.

#128 Add tentative support for unsupported colorspace for output
  Sources/BrightroomEngine/Engine/CoreGraphics+.swift
  Tests/BrightroomEngineTests/CGContextCreationTests.swift
Labels: Group: Enhancement

#132 Fix build of demo project
  Brightroom.xcodeproj/project.pbxproj
  Bundle/LUTs/Import LUT/Action.js
  Bundle/LUTs/Import LUT/ActionRequestHandler.swift
  Bundle/LUTs/Import LUT/Info.plist
  Bundle/LUTs/Import LUT/Media.xcassets/Contents.json
  Bundle/LUTs/Import LUT/Media.xcassets/TouchBarBezel.colorset/Contents.json
  Bundle/LUTs/ShareLUT/Base.lproj/MainInterface.storyboard
  Bundle/LUTs/ShareLUT/Info.plist
  Bundle/LUTs/ShareLUT/ShareViewController.swift
  Sources/Demo/Contents/DemoBuiltInEditorViewController.swift
  Sources/Demo/Contents/DemoCropMenuViewController.swift
  Sources/Demo/Contents/DemoImitationsViewController.swift
  Sources/Demo/Contents/DemoLUTViewController.swift
  Sources/Demo/Contents/DemoMaskingViewController.swift
  Sources/Demo/Contents/DemoPreviewViewController.swift
  Sources/Demo/Contents/Imitations/ImitationTinderViewController.swift
Labels: Group: Enhancement, Group: Fix Issue

#133 Create fallback on incorrect pixel format instead of validating images.
  Sources/BrightroomEngine/DataSource/ImageProvider.swift
  Sources/BrightroomEngine/DataSource/ImageSource.swift
  Sources/BrightroomEngine/Engine/CoreGraphics+.swift
  Sources/BrightroomEngine/Engine/ImageTool.swift
  Sources/BrightroomUI/Shared/Components/Crop/CropView.swift
  Sources/BrightroomUI/Shared/Components/ImageViews/CIImageDisplaying.swift
  Sources/Demo/Contents/DemoBuiltInEditorViewController.swift
  Sources/Demo/Contents/DemoCropMenuViewController.swift
  Sources/Demo/Contents/DemoImitationsViewController.swift
  Sources/Demo/Contents/DemoLUTViewController.swift
  Sources/Demo/Contents/DemoMaskingViewController.swift
  Sources/Demo/Contents/DemoPreviewViewController.swift
  Sources/SharedForDemo/Mocks.swift
  Sources/SwiftUIDemo/ContentView.swift
  Tests/BrightroomEngineTests/ImageSourceInitTest.swift
  Tests/BrightroomEngineTests/RendererOrientationTests.swift
  Tests/BrightroomEngineTests/RendererTests.swift
Labels: Group: Fix Issue, Tag: Breaking Change
